flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/enumerator/KafkaSourceEnumerator.java
flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/source/enumerator/KafkaEnumeratorTest.java

Fix error kafka partitionDiscoveryIntervalMs checking for noMoreNewSplits. This PR has been approved in [PR-22901](https://github.com/apache/flink/pull/22091)  just because kafka connector will be migrated from Flink main repo since 1.18 to here, so recreate it and close previous one in flink repo by commiters's suggestion.
Correct partitionDiscoveryIntervalMs checking for noMoreNewSplits with <=0
Add KafkaEnumeratorTest
#testRunWithDiscoverPartitionsOnceWithZeroMsToCheckNoMoreSplit,
#testRunWithDiscoverPartitionsToCheckNoMoreSplitOnce
#testRunWithPeriodicPartitionDiscoveryToCheckNoMoreSplitOnce
new cases and refine existed cases.
- Dependencies (does it add or upgrade a dependency): no
- The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
- The serializers: …

[FLINK-31319][connectors/kafka] Fix kafka new source partitionDiscoveryIntervalMs=0 cause bounded source can not quit

---

.github/workflows/push_pr.yml
.github/workflows/weekly.yml
pom.xml

1. Test CI builds against Flink 1.17.0 instead of Flink 1.17-SNAPSHOT
2. Run the weekly builds against 1.17-SNAPSHOT and 1.18-SNAPSHOT, while dropping 1.16-SNAPSHOT since it's incompatible with this version of the Flink Kafka connector
3. Set the correct groupId for `flink-connector-parent`
4. Remove `archunit` to avoid issues with the weekly builds, given that the version of Archunit can differ between Flink versions. Instead, it will rely on `flink-architecture-tests-test` dependencies.

[hotfix] Correct and/or synchronize multiple dependencies/versions

---

docs/content.zh/docs/connectors/table/kafka.md
docs/content.zh/docs/connectors/table/upsert-kafka.md
docs/content/docs/connectors/table/kafka.md
docs/content/docs/connectors/table/upsert-kafka.md

This PR fixes incorrect metadata column type in Kafka connector examples.
Changed timestamp metadata column type from TIMESTAMP to TIMESTAMP_LTZ (with local timezone) in [Kafka SQL connector examples](https://nightlies.apache.org/flink/flink-docs-release-1.15/docs/connectors/table/kafka/#how-to-create-a-kafka-table) in both English and Chinese docs.

[FLINK-32289][docs] Fix incorrect metadata column type in examples

---

flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/KafkaSource.java
flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/enumerator/AssignmentStatus.java
flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/enumerator/KafkaSourceEnumState.java
flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/enumerator/KafkaSourceEnumStateSerializer.java
flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/enumerator/KafkaSourceEnumerator.java
flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/enumerator/TopicPartitionAndAssignmentStatus.java
flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/source/enumerator/KafkaEnumeratorTest.java
flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/source/enumerator/KafkaSourceEnumStateSerializerTest.java

As described in [[FLIP-288](https://cwiki.apache.org/confluence/display/FLINK/FLIP-288%3A+Enable+Dynamic+Partition+Discovery+by+Default+in+Kafka+Source)](https://cwiki.apache.org/confluence/display/FLINK/FLIP-288%3A+Enable+Dynamic+Partition+Discovery+by+Default+in+Kafka+Source), the strategy used for new partitions is the same as the initial offset strategy, which is not reasonable.
According to the semantics, if the startup strategy is latest, the consumed data should include all data from the moment of startup, which also includes all messages from new created partitions. However, the latest strategy currently maybe used for new partitions, leading to the loss of some data (thinking a new partition is created and might be discovered by Kafka source several minutes later, and the message …

[FLINK-32019][Connector/Kafka]  EARLIEST offset strategy for partitions discoveried later based on FLIP-288

---

flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/enumerator/initializer/SpecifiedOffsetsInitializer.java
flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/enumerator/initializer/TimestampOffsetsInitializer.java

As described in [[FLIP-288](https://cwiki.apache.org/confluence/display/FLINK/FLIP-288%3A+Enable+Dynamic+Partition+Discovery+by+Default+in+Kafka+Source)](https://cwiki.apache.org/confluence/display/FLINK/FLIP-288%3A+Enable+Dynamic+Partition+Discovery+by+Default+in+Kafka+Source), Current JavaDoc does not fully explain the behavior of OffsetsInitializers. When the partition does not meet the condition, there will be a different offset strategy. 
This may lead to misunderstandings in the design and usage.
Add to SpecifiedOffsetsInitializer: "Use Specified offset for specified partitions while use commit offset or Earliest for unspecified partitions. Specified partition offset should be less than the latest offset, otherwise it will start from the earliest."
Add to …

[FLINK-32021][Connectors/Kafka] Improvement the Javadoc for SpecifiedOffsetsInitializer and TimestampOffsetsInitializer

---

flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/reader/KafkaSourceReader.java

As described in [FLINK-31208](https://issues.apache.org/jira/browse/FLINK-31208?filter=-2), an override method named pauseOrResumeSplits in KafkaSourceReader is redundant.
Just remove this redundant method.
The method content is same as its parent class SourceReaderBase, thus there is no influence to verify.

[FLINK-31208][Connectors/Kafka] KafkaSourceReader overrides meaninglessly a method(pauseOrResumeSplits)

---

.github/workflows/push_pr.yml
flink-connector-kafka/archunit-violations/86dfd459-67a9-4b26-9b5c-0b0bbf22681a

The reason we add new violation messages instead of update existing ones is that the patch of FLINK-31804 is only applied after Flink 1.18. We need to make sure the CI could run successfully for Flink versions before and after that.
If Kafka connector decides to drop support for versions before 1.18 in the future, please re-freeze the violations then.

[FLINK-33219][connector/kafka] Add new archunit violation messages introduced by FLINK-31804

---

flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/reader/KafkaSourceReader.java
flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/source/reader/KafkaSourceReaderTest.java

Prior to this fix, if the offsets to commit for a given checkpoint is empty, which can be the case if no starting offsets were retrieved from Kafka yet, then on checkpoint completion the cache is not properly evicted up to the given checkpoint.
This change fixes this such that in notifyOnCheckpointComplete, we shortcut the method execution to not need to try to commit the offsets since its empty anyways, and always remember to evict the cache up to the completed checkpoint.
I've modified the existing `KafkaSourceReaderTest#testCommitEmptyOffsets()` test to fail if the cache eviction fix was not applied. With this PR, that test now passes.

[FLINK-33231] [source] Properly evict offsetsToCommit cache on checkpoint complete if no offsets exist

---

pom.xml

Mitigate scanners flagging Flink or the Flink Kafka connector as vulnerable for CVE-2023-39410

[FLINK-33238][Formats/Avro] Upgrade used AVRO version to 1.11.3

---

.github/workflows/push_pr.yml
.github/workflows/weekly.yml

1. Test all PRs for `main` against all supported versions, meaning 1.17.x and 1.18.x. That's because only PRs run the dependency convergence check, and not nightly builds.
2. Make sure that we test nightlies against all supported versions (currently 1.17.x for the `v3.0` branch plus 1.17.x and 1.18.x against `main`)

[hotfix] Update CI strategy

---

docs/content.zh/docs/connectors/datastream/kafka.md
docs/content.zh/docs/connectors/table/kafka.md
docs/content.zh/docs/connectors/table/upsert-kafka.md
docs/content/docs/connectors/datastream/kafka.md
docs/content/docs/connectors/table/upsert-kafka.md
docs/data/kafka.yml

Currently, Kafka Connector official documentation has a bug in the download link and the version number.
This is the fix for https://issues.apache.org/jira/browse/FLINK-33401. 
The doc link with the bug is 
https://nightlies.apache.org/flink/flink-docs-release-1.18/docs/connectors/datastream/kafka/

[FLINK-33401][connectors/kafka] Fix the wrong download link and version in the connector doc

---

.github/workflows/push_pr.yml
.gitignore
flink-python/MANIFEST.in
flink-python/README.txt
flink-python/dev/integration_test.sh
flink-python/pom.xml
flink-python/pyflink/datastream/connectors/kafka.py
flink-python/pyflink/datastream/connectors/tests/test_kafka.py
flink-python/pyflink/pyflink_gateway_server.py
flink-python/setup.py
flink-python/tox.ini
pom.xml

Moves the `kafka.py` and the `kafka_test.py` code from the main Flink repository the connector repository.
When running `mvn clean install` downloads the testing infra scripts from the main Flink repo (`flink-python/dev/build-wheels.sh`, `flink-python/dev/install_command.sh`, `flink-python/dev/lint-python.sh`)
After that the tests could be run by the following commands:
```
cd flink-python
chmod a+x dev/* 
./dev/lint-python.sh -e mypy,sphinx
```
**Test changes**
The `kafka_test.py` had to be modified by adding [_check_latest_offsets_initializer](https://github.com/apache/flink-connector-kafka/pull/69/files#diff-c2fba8348f66807150d91656172726fb68bdfce68bfb067cc0c5a25da27d542dR359) because of [FLINK-28303](https://issues.apache.org/jira/browse/FLINK-28303) #52 
**Gateway server patch** …

[FLINK-33559] Externalize Kafka Python connector code

---

.github/workflows/push_pr.yml
.github/workflows/weekly.yml

The Flink Kafka connector now tests:
- All PRs against `main` are tested against Flink `1.17.2` and `1.18.1`, instead of `1.17.1` and `1.18.0`
- The weekly run tests -- `main` against `1.17-SNAPSHOT, `1.18-SNAPSHOT` and `1.19-SNAPSHOT` (1.19 is newly added) -- `v3.0` against `1.17-SNAPSHOT` and `1.18-SNAPSHOT` (as was before)

[hotfix] Synchronize CI pipeline setup

---

.github/workflows/push_pr.yml
.github/workflows/weekly.yml
flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/testutils/DataGenerators.java
flink-python/dev/integration_test.sh
flink-python/pyflink/flink-conf.yaml

This also includes dropping the weekly tests for the `v3.0` branch, since `v3.1` has been released and that's our main version going forward.

[FLINK-35007] Add support for Flink 1.19

---

.github/workflows/push_pr.yml
.github/workflows/weekly.yml

The PR will allow to differentiate between Kafka connector statistics and others with name ci

[FLINK-34961] Use dedicated CI name for Kafka connector to differentiate it in infra-reports

---

.github/workflows/push_pr.yml
.github/workflows/weekly.yml
flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/testutils/DataGenerators.java
flink-python/dev/integration_test.sh
flink-python/pyflink/flink-conf.yaml

Backport of https://github.com/apache/flink-connector-kafka/pull/90
(cherry picked from commit 897001d5682a0708042d59be81a10485ffd0dde7)

[FLINK-35007][BP v3.1] Add support for Flink 1.19 (#90)

---

flink-connector-kafka/pom.xml
flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/testutils/YamlFileMetadataService.java

SnakeYAML introduced breaking API changes and behavior changes between 1.31 and 2.2. This PR uses the updated APIs and explicitly allows the global tag for StreamMetadata (see changed SnakeYAML behavior in https://github.com/snakeyaml/snakeyaml/commit/2b8d47c8bcfd402e7a682b7b2674e8d0cb25e522).
* This dependency is only used in tests, so therefore not critical to address.
* Some tests are currently broken. Everything should be green once #90 goes in and this PR is rebased. I verified the change locally.
Closes #85.

[FLINK-35038] Bump `org.yaml:snakeyaml` to `2.2`

---

.github/workflows/push_pr.yml
.github/workflows/weekly.yml

This is a cherry-pick backport of https://github.com/apache/flink-connector-kafka/pull/92

[FLINK-34961][BP v3.1] Use dedicated CI name for Kafka connector to differentiate it in infra-reports

---

flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/dynamic/source/enumerator/DynamicKafkaSourceEnumerator.java
flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/dynamic/source/DynamicKafkaSourceITTest.java
flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/dynamic/source/enumerator/DynamicKafkaSourceEnumeratorTest.java
flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/DynamicKafkaSourceTestHelper.java

Saw some dormant code that was collecting `activeTopicPartitions` which got used nowhere. I believe the cleanup was already intended by the original developer, but just got lost for some reason.
So I've finished up the cleanup logic and added a test case to cover the issue in question.

[FLINK-35228][Connectors/Kafka] Fix: DynamicKafkaSource does not read re-added topic for the same cluster

---

flink-connector-kafka/archunit-violations/86dfd459-67a9-4b26-9b5c-0b0bbf22681a
flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/sink/KafkaWriter.java
flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/sink/KafkaWriterFaultToleranceITCase.java
flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/sink/KafkaWriterITCase.java
flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/sink/KafkaWriterTestBase.java

Fix the bug for losing data during kafka cluster is unavailable for a while.
The related issue: https://issues.apache.org/jira/browse/FLINK-35749 tells how to reproduce this bug.
The key problem is in WriterCallback#onCompletion of KafkaWriter:
```java
mailboxExecutor.submit(
() -> {
// Checking for exceptions from previous writes
checkAsyncException();
},
"Update error metric");
```
'mailboxExecutor.submit' without getting future back will not throw exception, which causes the 'asyncProducerException' is assign to null but the job seems like nothing happened. The fix is using 'mailboxExecutor.execute' instead of 'mailboxExecutor.submit'.
Added new test case KafkaWriterFaultToleranceITCase to cover this bug.
- Dependencies (does it add or upgrade a dependency): no
- The public API, i.e., …

[FLINK-35749] Kafka sink component will lose data when kafka cluster is unavailable for a while

---

flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/sink/KafkaRecordSerializationSchemaBuilder.java

In the CachingTopicSelector, a memory leak may occur when the internal logic fails to check the cache size due to a race condition. (https://github.com/apache/flink-connector-kafka/blob/d89a082180232bb79e3c764228c4e7dbb9eb6b8b/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/sink/KafkaRecordSerializationSchemaBuilder.java#L287-L289)
This PR fixes the memory leak by modifying the logic to be more resilient to failure.
Fix memory leak in CachingTopicSelector that can be triggered by race condition.
- By analyzing a Java heap dump, I identified a memory leak in the CachingTopicSelector. As in the screenshot, cache has 47,769 elements. If the internal logic were functioning correctly, the number of elements should be less than or equal to CACHE_RESET_SIZE (which is 5).
- …

[FLINK-33201][Connectors/Kafka] Fix memory leak in CachingTopicSelector

---

flink-connector-kafka/src/main/java/org/apache/flink/streaming/connectors/kafka/internals/AbstractFetcher.java

Fixing FLIP-471 in the old source would require some extra work, that we hopefully can avoid by removing the old source before doing the upgrade.

[FLINK-35886] Leave a note for future Flink 2.0 upgrade

---

flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/reader/KafkaPartitionSplitReader.java
flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/source/KafkaSourceITCase.java
flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/source/reader/KafkaSourceReaderTest.java
flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/testutils/KafkaSourceTestEnv.java
flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/KafkaTestBase.java
flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/KafkaTestEnvironment.java
flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/table/KafkaTableITCase.java
flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/table/KafkaTableTestBase.java

When using the flink kafka connector in batch scenarios, consuming transactional messages can cause indefinite hanging.
This issue can be easily reproduced with following steps. 
1. Produce transactional messages and commit them.
2. Configure `scan.bounded.mode` to `latest-offset` and run consumer using flink kafka connector
The previous stopping condition in the `KafkaPartitionSplitReader` compared the offset of the last record with the `stoppingOffset`. This approach works for streaming use cases and batch processing of non-transactional messages. However, in scenarios involving transactional messages, this is insufficient.      
[Control messages](https://kafka.apache.org/documentation/#controlbatch), which are not visible to clients, can occupy the entire range between the last …

[FLINK-34470][Connectors/Kafka] Fix indefinite blocking by adjusting stopping condition in split reader

---

flink-connector-kafka-e2e-tests/flink-end-to-end-tests-common-kafka/src/test/java/org/apache/flink/tests/util/kafka/SQLClientSchemaRegistryITCase.java
flink-connector-kafka-e2e-tests/flink-end-to-end-tests-common-kafka/src/test/java/org/apache/flink/tests/util/kafka/SmokeKafkaITCase.java
flink-connector-kafka-e2e-tests/flink-end-to-end-tests-common-kafka/src/test/resources/log4j2-test.properties
flink-connector-kafka/pom.xml
flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/dynamic/source/reader/DynamicKafkaSourceReader.java
flink-connector-kafka/src/main/java/org/apache/flink/streaming/connectors/kafka/internals/AbstractPartitionDiscoverer.java
flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/sink/FlinkKafkaInternalProducerITCase.java
flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/sink/KafkaSinkITCase.java
flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/sink/KafkaTransactionLogITCase.java
flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/sink/KafkaWriterTestBase.java
flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/testutils/DynamicKafkaSourceExternalContext.java
flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/testutils/KafkaUtil.java
flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/FlinkKafkaProducerMigrationTest.java
flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/KafkaConsumerTestBase.java
flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/KafkaTestBase.java
flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/KafkaTestEnvironmentImpl.java
flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/internals/metrics/KafkaMetricMutableWrapperTest.java
flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/table/KafkaTableTestBase.java
flink-connector-kafka/src/test/resources/log4j2-test.properties
pom.xml
tools/ci/log4j.properties

Currently, container logs appear under an o.a.f logger and thus are visible on CI. This results in compressed log size >40MB for a run and often leads to download errors.
This PR reroutes container logs to a special container logger. It also uses a custom format to significantly reduce the size of each log line. The logs for containers are disabled by default.
Here is the original log of an ITCase (308 KB)
[old.log](https://github.com/user-attachments/files/17010325/old.log)
```
2794 [docker-java-stream--2048098242] INFO  org.apache.flink.streaming.connectors.kafka.KafkaTestEnvironmentImpl [] - [Kafka-0] STDOUT: [2024-09-16 08:26:53,236] INFO Server environment:java.library.path=/usr/java/packages/lib:/lib:/usr/lib:/usr/lib64:/lib64 (org.apache.zookeeper.server.ZooKeeperServer)
2794 …
```

[FLINK-36278] Reduce log size

---

docs/content.zh/docs/connectors/datastream/kafka.md
docs/content/docs/connectors/datastream/kafka.md

Fix PyFlink jar download link.
* Use `py_connector_download_link` shortcode to generate link with correct connector artifact version, instead of Flink version.
* Generated documentation locally
* Dependencies (does it add or upgrade a dependency): no
* The public API, i.e., is any changed class annotated with `@Public(Evolving)`: no
* The serializers: no
* The runtime per-record code paths (performance sensitive): no
* Anything that affects deployment or recovery: JobManager (and its components), Checkpointing, Kubernetes/Yarn, ZooKeeper: no
* The S3 file system connector: no

[FLINK-36422][docs] Fix PyFlink jar download link

---

.mvn/wrapper/maven-wrapper.properties
mvnw
mvnw.cmd

Adds maven wrapper to ease future maintenance.

[hotfix] Add maven wrapper

---

docs/data/kafka.yml

Fix connector release flink compatibility configuration for documentation build to render released artifact version correctly.

[FLINK-36595][docs] Explicitly set connector compatibility as string to prevent version comparison mismatch

---

flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/KafkaSourceBuilder.java
flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/source/KafkaSourceBuilderTest.java

Currently Kafka source enables partition discovery. This is set by partition.discovery.interval.ms, aka KafkaSourceOptions.PARTITION_DISCOVERY_INTERVAL_MS. The default value is 5 minutes, which is equal to the default value of metadata.max.age.ms in Kafka.
However, it's disabled by default unexpectedly in the source builder ([code](https://github.com/apache/flink-connector-kafka/blob/main/flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/KafkaSourceBuilder.java#L476-L480)). The intention I believe was to only disable for bounded source.
We need a fix that is able to keep the default partition discovery. This could cause data loss after Kafka retention if the new partitions are not consumed silently.

[FLINK-36780] Kafka source disables partition discovery unexpectedly

---

flink-python/setup.py

Inspired by [Multiple top-level packages discovered in a flat-layout](https://stackoverflow.com/questions/72294299/multiple-top-level-packages-discovered-in-a-flat-layout) , add `py_modules=[]` to fix python CI test [FLINK-37396](https://issues.apache.org/jira/browse/FLINK-37396).

[FLINK-37396] Fix setup.py: multiple top-level packages discovered in a flat-layout

---

flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/sink/KafkaSinkBuilder.java
flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/sink/KafkaSinkBuilderTest.java
flink-connector-kafka/src/test/java/org/apache/flink/streaming/connectors/kafka/table/KafkaChangelogTableITCase.java
flink-python/pyflink/datastream/connectors/tests/test_kafka.py

As described in https://issues.apache.org/jira/browse/FLINK-37380 , though org.apache.flink.connector.kafka.sink.KafkaSinkBuilder#sanityCheck said `EXACTLY_ONCE delivery guarantee requires a transactionIdPrefix to be set to provide unique transaction names across multiple KafkaSinks writing to the same Kafka cluster` ,  it 's no use because the transactionalIdPrefix with a default value "kafka-sink" will never be null.
This PR just remove the default value, and make the sanityCheck valid.

[FLINK-37380] Change TransactionalIdPrefix to a required option if Exactly once 

---

flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/source/reader/KafkaPartitionSplitReader.java
flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/source/reader/KafkaPartitionSplitReaderTest.java

FLINK-34470 introduced a new consumer.position call that was not wrapped by retryOnWakeUp, differently than the rest of calls ont he class.
It was generating random WakeupExceptions on our production code for Flink19.
Trivial code change. But I extracted this to a method so i could add a simple test for all the calls

[FLINK-36630][Connectors/Kafka] Wrap consumer.position in retryOnWakeup

---

flink-connector-kafka-e2e-tests/flink-end-to-end-tests-common-kafka/pom.xml
flink-connector-kafka-e2e-tests/flink-streaming-kafka-test-base/pom.xml
flink-connector-kafka-e2e-tests/flink-streaming-kafka-test/pom.xml
flink-connector-kafka-e2e-tests/pom.xml
flink-connector-kafka/pom.xml
flink-python/pom.xml
flink-sql-connector-kafka/pom.xml
pom.xml

Update flink-connector-kafka version to 4.0-SNAPSHOT to support Flink 2.0

[FLINK-37144] Update version to 4.0-SNAPSHOT.

---

flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/dynamic/source/enumerator/DynamicKafkaSourceEnumerator.java

To avoid displaying a large amount of connection information.

[FLINK-37304] Reduce the log level about metadataUpdateEvent in DynamicKafkaSourceEnumerator.

---

flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/sink/ExactlyOnceKafkaWriterITCase.java
flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/sink/KafkaWriterFaultToleranceITCase.java
flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/sink/KafkaWriterTestBase.java
flink-connector-kafka/src/test/resources/log4j2-test.properties

Deflake ExactlyOnceKafkaWriterITCase#shouldAbortLingeringTransactions
The test was actually not working correctly since writer's get their unique prefix (pool rework PR). The test mostly succeeded since the partitions in which records were written was non-deterministic and more often than not the 3 records didn't meet in the 10 partitions which resulted in an incorrect pass.
Now the value is also passed as a key, which makes partitions assignment deterministic and for this test we just write the exact same value 3 times.

[FLINK-37611] Deflake ExactlyOnceKafkaWriterITCase

---

flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/sink/ExactlyOnceKafkaWriter.java
flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/sink/KafkaCommitter.java
flink-connector-kafka/src/main/java/org/apache/flink/connector/kafka/sink/KafkaWriter.java
flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/sink/FlinkKafkaInternalProducerITCase.java

Transaction abortion can take a while. Apparently, task cleanup may not trigger correctly if this abortion is interrupted (for some unrelated reason). This leaks producers. The fix is to close() manually during initialization of the EOS writer until we fixed the Flink bug FLINK-37612.

[FLINK-37613] Fix resource leak during abortion

---

flink-connector-kafka/src/test/java/org/apache/flink/connector/kafka/testutils/DockerImageVersions.java
flink-sql-connector-kafka/src/main/resources/META-INF/NOTICE
pom.xml

This PR:
- Updates the Kafka client libraries to 3.9.1. This release has numerous bug and performance fixes as well as several CVE fixes, notably [CVE-2025-27817](https://nvd.nist.gov/vuln/detail/CVE-2025-27817).
- Updates the various confluent library and containers versions to 7.9.2 which matches the Kafka 3.9.x releases.
- Updates the test containers and docker-java-api version to fix podman support for the integrations tests.
- Addresses #179

[FLINK-37983] Update to Kafka client 3.9.1 

---

flink-connector-kafka-e2e-tests/flink-end-to-end-tests-common-kafka/pom.xml
flink-connector-kafka-e2e-tests/flink-streaming-kafka-test-base/pom.xml
flink-connector-kafka-e2e-tests/flink-streaming-kafka-test/pom.xml
flink-connector-kafka-e2e-tests/pom.xml
flink-connector-kafka/pom.xml
flink-python/pom.xml
flink-sql-connector-kafka/pom.xml
pom.xml

During the release, we accidentally overwrote the snapshot version on the branch.  The fixed versions are only meant to be used on release tags but not on the active branches.

[hotfix] Set version to 4.0-SNAPSHOT
